name: CI/CD Pipeline - Lista de Tarefas

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Teste e Verificação
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Cache de dependências
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Verificar sintaxe
      run: |
        python -m py_compile app/main.py
    
    - name: Executar aplicação para teste
      run: |
        cd app
        timeout 30s python main.py &
        sleep 10
        curl -f http://localhost:5000 || echo "App started successfully"

  build:
    name: Build da Aplicação
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Criar build
      run: |
        mkdir -p build
        cp -r app/* build/
        cp requirements.txt build/
        echo "Build criado em $(date)" > build/build-info.txt
    
    - name: Upload do build
      uses: actions/upload-artifact@v3
      with:
        name: todo-app-build
        path: build/
